os: linux
  #- osx # [2018-12-07] No services on OSX (docker)
  #- windows # [2018-12-07] Fix image, paths for Windows

dist: []

addons:
  apt:
    packages:
      - realpath

sudo: false

services:
  - docker

language: shell
#language: go

env:
  matrix: []
  global:
    - NS_NAME=bvberkum
    - APP_ID=x-ci
    - BUILD_GOARCH="386 amd64 arm" 
    - BUILD_GOOS="linux" 
    - DO_GITHUB_DEPLOY=1
    - DOCKER_USERNAME=$NS_NAME
    - secure: "qT1SeCagJrYJ7mIo3dvtjAZtZLcHVqpJMh6M7hbo+5vKDPE+TZqFjKhiwt/9cw37vG2wgBnYHY2wl2Uenw1LzWkHaKsjtRQ2xqiGc7iXffaaKUOkf75YA0cvppfVXIRwb/ZkIbA0ZOWCeEM9qvCA2rsmGmud1ksxbP0kotkwHpjwsxexaq6JoKRe1EuEBDR4hCkfUN5fFDnzkFyscWtSpgnO1/Z0/pn2zY85Q1M+I4n1X9w5PoXiJ+cQZGenQqhNVoEio4NKKiUCbQDjYaMY186fPnJhR0LraK6V7rdG+btTXyiZ2TWnx9Je8AZO/6Bfc16pySCdS6inkxqZtQjtdttTiGHkHi4n7YuS7GfQNetqbUu9nyRjFiDyGFLbSJy9HussTjIh6QXN+OnDxbW9WNcLmLWOoB4+TxF70TqYkQzsHwyB8KSGaQO9m/0/DmXkSnj+ezvLeXbKHFunQUKbzlgQdul7P1iIrVDbh82CbWhJjjXf1G6vGp3SAA43ye9bt8SVPpl5efX65t1XjfhE6NYgjTi66az07BDE/jBz61wvfPvmt8OWX/FwVqZQEg3le6fKXy8AxyCzu6+p4sXpnrKnlvf5IK02ZspCpx5boHvk0KderJRmyzoqWb9k0HKAaBYRB6fQe5JuAU6eP5btJG+rkBV7n4bnrY1yhEDVI+o="
    - secure: "doTHGAFPV2Siss5rtBXsZLP4Rbe6qSRJPbFL8pSCGPC44J5ORVkjmlIzY1MPKUjVsKlXXWnHebuNj2jHkFXdRSGPpTELUk3tsnGAA0AInuwWiIIjZJ8iHUfsI0czyX1cuLOfJG7Ql56TyGcEnlUaNdsiX3gG3kKr48FcqQSpmpbEVK1VZsUKNY7co+2utayMsOh1AcDr2uTOxeXimP1yydff5N0wh24F1b/+vAOrkeocowynx+cdsluKX0V0GvnSdzn5YzZSUMjpi/NVGN1QsvE05lHhUL/95uEI8EbdLtSgkkcDcaU2JPNx515IbgC/440B0OHFs77ugUbKtsgMtOB9VRso4aKVi5rBbGVzK3XkejWnW17Ezjk+0wRWNWOqEjN2uiYzqfcP0py/uml32zHnovif7GqVpvOQGR+/HprPTg5U5l/d2+dt2ivCkkCMUmcUNWx4DaaNS5AraBgbKxK5tZAKTevj/DjJ1FfrnjurYXBazF2dH8rJHOMB+DtXbLUlzm5z5uM1fWbs37Anvru5i/+YVxQ+wmyB0Zil/XhD46pvRmCLn5D6GRVKfInp0vD7HtHTWM0n8VG8YWr9vdHXl6evFdyd+lfN++1+xvYq6fW38MINnpmDiBMX4aD0GHPfjzY3BZuWQmTCFK05ea83vl8GKbD+JdRTVBN/9ko="

before_install:
  - . ./tools/ci/before-install.sh

install:
  - . ./tools/ci/install.sh

before_script:
  - . ./tools/ci/before.sh

script:
  - . ./tools/ci/script.sh

before_cache:
  - . ./tools/ci/before-cache.sh

cache:
  directories:
     - .htd
     - $HOME/.local
     - $HOME/.basher
     - $HOME/.statusdir/

after_success:
  - . ./tools/ci/after-success.sh

#matrix:
#  include: []
#  exclude: []

branches:
  only: []
  except: []

# GitHub release upload
#before_deploy:
#  - export RELEASE_PKG_FILE=$(echo $APP_ID* | awk '{print $1}')
#  - test -e "$RELEASE_PKG_FILE" && export FILE_EXISTS=1 || export FILE_EXISTS=0
#  - test $FILE_EXISTS -eq 1 && echo "deploying $RELEASE_PKG_FILE to GitHub releases" || echo "nothing to deploy to github $RELEASE_PKG_FILE"
  
deploy:
  provider: releases
  api_key:
    secure: P5R2MJWoSgr8Ej8iMXNwhU4GVKGbwA6J3X9LnacPMsvHwLJCj4SIYPPeuNn5ASXJGzN6zX56y7NoCR3XI5s1LJeUJPRl74YKtq4Ckok+RjOEtWzz3G/EgzHuEJlHuBUDlRNTpi49S96PGZUdHmIpkKSzA4NFtcCB+AQYn0cFM+L0gm0hbygfIQQU+g8P9Mj877mW9NUq3sWaVqKRpuR0NNB21QHMDH2BPQKUkqRePKPi+VCNqAccuEm7NduNJ3NgKqkJ4s/NUgsliBHqo75uOJT7BzUGkT/gZsU+Th+M7t5jyBNJIv0obHpsu4MldBcb5iPNm1NBOzp5rBBAS/dalfYdHEVoe7pndkom+Tem4Lj6V16rbchba9no/Qt9b+SI/bdZsGquDy/FVYfgcx/1sgfWFLLvwD//k1jT3eAwtfF4OAlyaHXuYrnLOmfI0e0nGurJ4B9yjHuLnWr/COneQFYn11qvGZRNT006tyImEc+7oS8kLpyurTm6Y3KqEu1oN8PTwITaGUyypp0OoNMre2IdvbRarTN5pxsPD2kWs1Hl3i1pOyRj7kt6I8gjd4w6iTdVfXnbKwZu9l0wC9HkuVsDX/Ex9Gorz9qDNdUHeBPxyh1qG7wsxZz0TtVQlpM4vZoBfjv1b+puWDiHVytnDVwVEIYKkndSvKwiaTfUlBQ=
  skip_cleanup: true
  file:
    - $APP_ID-linux-amd64
    - $APP_ID-linux-386
    - $APP_ID-linux-arm
  on:
    repo: $NS_NAME/$APP_ID
    # NOTE: makes drafts but seems to err? branch: dev
    tags: true # Create releases from version tags always seems to work
    # FIXME conditional publish, try to prevent error
    condition: $DO_GITHUB_DEPLOY = 1

# Copy: U-S:
