jobs:
  build:
    # Circle CI (base image):
    # Each command line is run in `/bin/bash -eo pipefail`.
    # The start dir is ~/project, there is a helper to create the checkout
    #
    #docker:
    #  - image: cimg/base:2020.01

    machine: true

    steps:

    - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

# Id: X-CI:circleci/config.yml
